/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { UserPointInfoFindManyArgs } from "../../userPointInfo/base/UserPointInfoFindManyArgs";
import { UserPointInfo } from "../../userPointInfo/base/UserPointInfo";
import { UserPointInfoWhereUniqueInput } from "../../userPointInfo/base/UserPointInfoWhereUniqueInput";
import { UserAnswerResulFindManyArgs } from "../../userAnswerResul/base/UserAnswerResulFindManyArgs";
import { UserAnswerResul } from "../../userAnswerResul/base/UserAnswerResul";
import { UserAnswerResulWhereUniqueInput } from "../../userAnswerResul/base/UserAnswerResulWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        roles: true,
        oauthType: true,
        openId: true,
        sessionKey: true,
        unionId: true,
        sessionId: true,
        phone: true,
        mobileType: true,
        nickName: true,
        avatarUrl: true,
        gender: true,
        birthday: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        roles: true,
        oauthType: true,
        openId: true,
        sessionKey: true,
        unionId: true,
        sessionId: true,
        phone: true,
        mobileType: true,
        nickName: true,
        avatarUrl: true,
        gender: true,
        birthday: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        roles: true,
        oauthType: true,
        openId: true,
        sessionKey: true,
        unionId: true,
        sessionId: true,
        phone: true,
        mobileType: true,
        nickName: true,
        avatarUrl: true,
        gender: true,
        birthday: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          username: true,
          roles: true,
          oauthType: true,
          openId: true,
          sessionKey: true,
          unionId: true,
          sessionId: true,
          phone: true,
          mobileType: true,
          nickName: true,
          avatarUrl: true,
          gender: true,
          birthday: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          firstName: true,
          lastName: true,
          username: true,
          roles: true,
          oauthType: true,
          openId: true,
          sessionKey: true,
          unionId: true,
          sessionId: true,
          phone: true,
          mobileType: true,
          nickName: true,
          avatarUrl: true,
          gender: true,
          birthday: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/userPointInfos")
  @ApiNestedQuery(UserPointInfoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserPointInfo",
    action: "read",
    possession: "any",
  })
  async findManyUserPointInfos(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserPointInfo[]> {
    const query = plainToClass(UserPointInfoFindManyArgs, request.query);
    const results = await this.service.findUserPointInfos(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userPointInfos")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectUserPointInfos(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserPointInfoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userPointInfos: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userPointInfos")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateUserPointInfos(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserPointInfoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userPointInfos: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userPointInfos")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectUserPointInfos(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserPointInfoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userPointInfos: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/userAnswerResuls")
  @ApiNestedQuery(UserAnswerResulFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserAnswerResul",
    action: "read",
    possession: "any",
  })
  async findManyUserAnswerResuls(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserAnswerResul[]> {
    const query = plainToClass(UserAnswerResulFindManyArgs, request.query);
    const results = await this.service.findUserAnswerResuls(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },

        answerResult: true,
        lastUpdateUserId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userAnswerResuls")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async connectUserAnswerResuls(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserAnswerResulWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAnswerResuls: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userAnswerResuls")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateUserAnswerResuls(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserAnswerResulWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAnswerResuls: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userAnswerResuls")
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async disconnectUserAnswerResuls(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserAnswerResulWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAnswerResuls: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
