/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsJSON, ValidateNested } from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserPointInfoCreateNestedManyWithoutUsersInput } from "./UserPointInfoCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { UserAnswerResulCreateNestedManyWithoutUsersInput } from "./UserAnswerResulCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSON()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserPointInfoCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserPointInfoCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserPointInfoCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userPointInfos?: UserPointInfoCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserAnswerResulCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserAnswerResulCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserAnswerResulCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userAnswerResuls?: UserAnswerResulCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
